export const SEARCH_INDEX = 'SEARCH_INDEX'
export const ENRICH_SEARCH_RESULT = 'ENRICH_SEARCH_RESULT'
export const MIGRATE_PROFILE = 'MIGRATE_PROFILE'
export const MIGRATE_NAME = 'MIGRATE_NAME'
export const ADD_TO_NAME_INDEX = 'ADD_TO_NAME_INDEX'
export const PARTIAL_UPDATE_OBJECT = 'PARTIAL_UPDATE_OBJECT'


