export const ADD_PROFILE_LINK = 'ADD_PROFILE_LINK'
export const EDIT_PROFILE_LINK = 'EDIT_PROFILE_LINK'
export const REMOVE_PROFILE_LINK = 'REMOVE_PROFILE_LINK'
export const ADD_CREDIT = 'ADD_CREDIT'
